apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-web-api
  labels:
    app: web-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: web-api
        image: dekkusu/devops-things:caplinq
        imagePullPolicy: Always
        ports:
        - containerPort: 80