apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-web-deployment
  labels:
    app: web-api-deployment
  namespace: dotnet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-api-deployment
  template:
    metadata:
      labels:
        app: web-api-deployment
      namespace: dotnet
    spec:
      containers:
      - name: web-api-deployment
        image: dekkusu/devops-things:caplinq
        imagePullPolicy: Always
        ports:
        - containerPort: 80