apiVersion: v1
kind: Service
metadata:
  name: dotnet-web-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "2"
  labels:
    app: web-api-service
  namespace: dotnet
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-api-service
  sessionAffinity: None