apiVersion: v1
kind: Service
metadata:
  name: dotnet-web-api
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "2"
  labels:
    app: web-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-api
  sessionAffinity: None