name: dotnet CI/CD pipeline
on:
  push:
    branches:
      - 'main'

env:
    DOCKER_USER: ${{ secrets.DOCKER_USER }}
    DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup docker
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Repo
        run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./Caplinq.DevOps
          push: true
          tags: dekkusu/devops-things:caplinq

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Restart Kubernetes Deployment
        run:  kubectl rollout restart deployments -n dotnet
     
