name: dotnet CI/CD pipeline
on:
  push:
    branches:
      - 'main'

env:
    DOCKER_USER: ${{ secrets.DOCKER_USER }}
    DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Install dependencies
        run: dotnet restore /Caplinq.DevOps/Caplinq.DevOps.sln

      - name: Build dotnet
        run: dotnet build /Caplinq.DevOps/Caplinq.DevOps.sln

      - name: Test dotnet
        run: dotnet test /Caplinq.DevOps/Caplinq.DevOps.sln

      - name: Setup docker
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Repo
        run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./Caplinq.DevOps
          push: true
          tags: dekkusu/devops-things:caplinq

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Restart Kubernetes Deployment
        run:  kubectl rollout restart deployments -n dotnet
     
